# Generated by Django 5.0.2 on 2025-11-24 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comparison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merged_path', models.CharField(max_length=512)),
                ('notes', models.TextField(blank=True)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges', to='comparison.comparisonsession')),
            ],
        ),
    ]
