# Generated by Django 5.0.2 on 2025-11-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('left_path', models.CharField(max_length=512)),
                ('right_path', models.CharField(max_length=512)),
                ('diff_summary', models.TextField(blank=True)),
                ('merged_path', models.CharField(blank=True, max_length=512)),
            ],
        ),
    ]
